### ISSUE TITLE
Dotnet allocation profiler support

### ISSUE THREAD

**Issue by kelltrick** [dotnet/dotnet-monitor#778]
- [x] #779 Prototype loading allocation profiler
- [x] #780 Design integration for allocation profiler
- [x] #781 Add support for loading profilers
- [x] #782 Allow startup trigger to process sync
- [x] #783 Add trace profiler for allocations to trace endpoint
